---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccountname }}
  labels:
    app: {{ .Release.Name }}-spbak8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rolename }}
  labels:
    app: {{ .Release.Name }}-spbak8s
rules:
 - apiGroups:
   - ""  
   resources:
   - pods
   verbs:
   - create
   - get
   - list
   - watch
 - apiGroups:
   - ""  
   resources:
   - endpoints
   - services
   verbs:
   - get
   - list
   - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rolebindingname }}
  labels:
    app: {{ .Release.Name }}-spbak8s
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccountname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rolename }}
---