apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-admin-k8s-service-account
  labels:
    app: spring-boot-admin-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-boot-admin-k8s-role
  labels:
    app: spring-boot-admin-k8s
rules:
 - apiGroups:
   - ""  
   resources:
   - pods
   verbs:
   - create
   - get
   - list
   - watch
 - apiGroups:
   - ""  
   resources:
   - endpoints
   - services
   verbs:
   - get
   - list
   - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-boot-admin-k8s-role-binding
  namespace: springbootadmin
  labels:
    app: spring-boot-admin-k8s
subjects:
- kind: ServiceAccount
  name: spring-boot-admin-k8s-service-account
  namespace: springbootadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-boot-admin-k8s-role
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin-k8s-webservice
  labels:
    app: spring-boot-admin-k8s
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: 8080-tcp
  selector:
    app: spring-boot-admin-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin-k8s-actuator
  labels:
    app: spring-boot-admin-k8s
    type: actuator
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: 8081-tcp
  selector:
    app: spring-boot-admin-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-admin-k8s-deployment
  labels:
    app: spring-boot-admin-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-admin-k8s
  replicas: 1
  template:
    metadata:
      name: spring-boot-admin-k8s-deployment
      labels:
        app: spring-boot-admin-k8s
    spec:
      serviceAccountName: spring-boot-admin-k8s-service-account
      imagePullSecrets:
        - name: eroski-portus
      containers:
        - name: spring-boot-admin-k8s-container
          image: spring-boot-admin-k8s:0.0.0
          env:
            - name: spring.cloud.kubernetes.discovery.service-labels.type
              value: actuator
            - name: spring.security.user.name
              value: springbootadmin
            - name: spring.security.user.password
              value: password
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1